adding users

diff --git a/files/entrypoint b/files/entrypoint
--- a/files/entrypoint
+++ b/files/entrypoint
@@ -1,12 +1,38 @@
-#!/bin/sh
-
-#if [ $1 = "preconfigured" ]; then
-#    exec /usr/sbin/sshd -D -e
-#fi
-# -D Do not detach and become daemon.
-#  -e Write debug logs to standard error. This could be used for debugging.
+#!/bin/bash
 
 set -Eeo pipefail
 
 # shellcheck disable=2154
-#trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+
+if [ -n "$USER1" ]; then
+	IFS=':' read -ra userargs <<< "$USER1"
+    username="${userargs[0]}"
+    password="${userargs[1]}"
+
+    log "adding user"
+    useradd -m "$username"
+    echo "$username:$password" | chpasswd
+    chown root:root "/home/$username"
+    chmod 755 "/home/$username"
+    usermod -aG ssh -d /home "$username"    
+fi
+
+if [ -n "$USER2" ]; then
+	IFS=':' read -ra userargs <<< "$USER1"
+    username="${userargs[0]}"
+    password="${userargs[1]}"
+
+    log "adding user"
+    useradd -m "$username"
+    echo "$username:$password" | chpasswd
+    chown root:root "/home/$username"
+    chmod 755 "/home/$username"
+    usermod -aG ssh -d /home "$username"    
+fi
+
+log "Starting sshd"
+exec /usr/sbin/sshd -D -e
+
+# -D Do not detach and become daemon.
+#  -e Write debug logs to standard error. This could be used for debugging.
